# ...existing code...

def submit_claim(request):
    # ...existing code...
    if request.method == 'POST':
        form = ClaimForm(request.POST)
        if form.is_valid():
            claim = form.save(commit=False)
            # ...existing code...
            claim.incognito = form.cleaned_data.get('incognito', False)
            claim.save()
            # ...existing code...
    # ...existing code...

def browse_claims(request):
    # ...existing code...
    claims = Claim.objects.filter(incognito=False)
    # ...existing code...
